version: "3"
services:
  flask:
    container_name: isla_src
    image: flask
    ports:
      - "5002:5000"
    volumes:
      - ./:/app
    depends_on:
      - db
    tty: true

  db:
    container_name: isla_db
    image: postgres:12.0
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"