"""test de migration

Revision ID: 1764265e6410
Revises: 
Create Date: 2019-10-12 17:18:42.492115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1764265e6410'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('themes', 'date_creation',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('themes', 'date_creation',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
