"""empty message

Revision ID: 48012cb4b1f7
Revises: 687fa2427072
Create Date: 2019-09-08 15:27:03.110740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48012cb4b1f7'
down_revision = '687fa2427072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_model_name'), 'role_model', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_model_name'), table_name='role_model')
    op.drop_table('role_model')
    # ### end Alembic commands ###
