"""empty message

Revision ID: 638445acb1db
Revises: 48012cb4b1f7
Create Date: 2019-09-08 15:49:45.198816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638445acb1db'
down_revision = '48012cb4b1f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=80), nullable=False),
    sa.Column('resume', sa.String(length=100), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('is_brouillon', sa.Boolean(), nullable=True),
    sa.Column('is_archive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('themes')
    # ### end Alembic commands ###
